#!/usr/bin/env bash
set -ex

# install code ocean aux tools
mkdir -p /opt
cd /opt
git clone https://github.com/codeocean/co_aux_tools.git
cd co_aux_tools/
# git checkout #######  # uncomment and replace with commit hash to pin version
chmod +x {g,s}et_*
ln -s $PWD/{g,s}et_*.py /usr/local/bin
